language: common-lisp
sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl
    - LISP=allegro
    - LISP=cmucl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=clisp

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove
  - git clone https://github.com/fukamachi/sxql ~/lisp/sxql

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - t/init.sh
  - ros --version
  - ros config

script:
  - run-prove mito-test.asd
